# Travis CI configuration file.

language: php

php:
    # 5.6
    - 7.0
# faster builds on new travis setup not using sudo
sudo: false

install:
  - pwd
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - composer show -i

before_script:
    - pwd && ls
script:
    - codecept run unit
    # vendor/bin/codecept -c vendor/pceuropa/yii2-forms run unit
after_failure:
    # cat codeception/_app/runtime/logs/*
